CREATE SMALLFILE TABLESPACE rts42cfg0I LOGGING DATAFILE '/oracle/db/fortytwo/rts42cfg0I.dbf'
SIZE 10M
SEGMENT SPACE MANAGEMENT AUTO
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
online;

CREATE SMALLFILE TABLESPACE rts42cfg0D LOGGING DATAFILE '/oracle/db/fortytwo/rts42cfg0D.dbf'
SIZE 10M
SEGMENT SPACE MANAGEMENT AUTO
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
online;

CREATE SMALLFILE TABLESPACE rts42dat0D LOGGING DATAFILE '/oracle/db/fortytwo/rts42dat0D.dbf'
SIZE 10M
SEGMENT SPACE MANAGEMENT AUTO
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
online;

CREATE SMALLFILE TABLESPACE rts42dat0I LOGGING DATAFILE '/oracle/db/fortytwo/rts42dat0I.dbf'
SIZE 10M
SEGMENT SPACE MANAGEMENT AUTO
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
online;

CREATE SMALLFILE TABLESPACE rts42log0D LOGGING DATAFILE '/oracle/db/fortytwo/rts42log0D.dbf'
SIZE 10M
SEGMENT SPACE MANAGEMENT AUTO
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
online;

CREATE SMALLFILE TABLESPACE rts42log0I LOGGING DATAFILE '/oracle/db/fortytwo/rts42log0I.dbf'
SIZE 10M
SEGMENT SPACE MANAGEMENT AUTO
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
online;

CREATE SMALLFILE TABLESPACE rts42his0D LOGGING DATAFILE '/oracle/db/fortytwo/rts42his0D.dbf'
SIZE 10M
SEGMENT SPACE MANAGEMENT AUTO
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
online;

CREATE SMALLFILE TABLESPACE rts42his0I LOGGING DATAFILE '/oracle/db/fortytwo/rts42his0I.dbf'
SIZE 10M
SEGMENT SPACE MANAGEMENT AUTO
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
online;
