CREATE USER appp42 IDENTIFIED BY DBA
/
GRANT p42adm TO appp42
/
GRANT UNLIMITED TABLESPACE TO appp42
/
ALTER USER appp42 DEFAULT ROLE ALL
/


CREATE USER fortytwo IDENTIFIED BY fortytwopw
/
GRANT p42user TO fortytwo
/
