CREATE ROLE p42ro NOT IDENTIFIED;
/
GRANT CREATE SESSION TO p42ro;
/

CREATE ROLE p42rw NOT IDENTIFIED;
/
GRANT CREATE SESSION TO p42rw;
/

CREATE ROLE p42user NOT IDENTIFIED;
/
GRANT CREATE SESSION TO p42user;
/

CREATE ROLE p42app NOT IDENTIFIED;
/
GRANT CREATE SESSION TO p42app;
/

CREATE ROLE p42adm NOT IDENTIFIED;
/
GRANT CREATE SESSION TO p42adm;
/
GRANT CREATE TABLE     TO p42adm;
/
GRANT QUERY REWRITE    TO p42adm;
/
GRANT CREATE VIEW      TO p42adm;
/
GRANT CREATE SEQUENCE  TO p42adm;
/
GRANT CREATE TRIGGER   TO p42adm;
/
GRANT CREATE PUBLIC SYNONYM TO p42adm;
/
GRANT CREATE TYPE TO p42adm;
/
